# Change these first
owner: ucytech # Your GitHub organization or username, where this repository lives
repo: ThinHoc-Status # The name of this repository

sites:
  - name: ThinHoc Website
    url: https://www.thinhoc.com
  - name: ThinHoc Testflight
    url: https://launch.thinhoc.com/status
    expectedStatusCodes:
      - 200
  - name: ThinHoc API
    url: https://api.thinhoc.com/v1/ping


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.thinhoc.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/ucytech/ThinHoc-status/master/assets/101_thinhoc_white.png
  themeUrl: https://status.thinhoc.com/theme.css
  name: ThinHoc
  introTitle: "Monitor the system status of **ThinHoc** and receive updates on outages in realtime."
  introMessage: "Monitor the system status of **ThinHoc** and receive updates on outages in realtime."
  navbar:
    - title: Website
      href: https://www.thinhoc.com
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: Powered by [Upptime](https://upptime.js.org)

skipDescriptionUpdate: true

commitMessages:
  commitAuthorName: "ThinHoc Status Bot"
  commitAuthorEmail: "status@thinhoc.com"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
